version: "2"
services:
  mongo:
    image: "mongo:3.2"
    hostname: mongo
    expose:
      - "27017"
    dns:
      - 172.20.0.5
    networks:
      static-network:
        ipv4_address: 172.20.0.3

  bind:
    image: "sameersbn/bind:9.11.3-20180713"
    hostname: ns
    expose:
      - "53"
    ports:
     # - "53:53"
      - "10000:10000"
    dns:
      - 172.20.0.5
      - 8.8.8.8
    environment:
      - ROOT_PASSWORD=generated-password
    command: /contrib/scripts/docker-compose/update_bind.sh
    #stdin_open: true
    #tty: true
    volumes:
      - "./contrib/:/contrib"
    networks:
      static-network:
        ipv4_address: 172.20.0.5

  mail:
    image: "esminis/mail-server-postfix-vm-pop3d"
    hostname: mail
    expose:
       - "25"
       - "465"
       - "995"
    ports:
      - "8443:8443"
      - "25:25"
      - "465:465"
      - "995:995"
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    depends_on:
      - bind
    volumes:
      - "./contrib/:/contrib"
    command: bash -c 'cp /contrib/scripts/sasl/sasldb2 /etc/ && cp -r /contrib/scripts/tequila/* /opt/tequila/domains/ && chown -R tequila:tequila /opt/tequila/domains && mkdir -p /var/spool/virtual/ci-doichain.org && chown tequila:tequila /var/spool/virtual/ci-doichain.org && service postfix reload && sleep infinity'
    networks:
      static-network:
        ipv4_address: 172.20.0.4

  alice:
    image: "doichain/node-only:0.16.3.2"
    hostname: alice
    ports:
      - "18543:18332"
    expose:
      - "18332"
    environment:
      - REGTEST=true
      - RPC_ALLOW_IP=::/0
      - RPC_PASSWORD=generated-password
      - DAPP_URL=http://172.20.0.8:3000/
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.6

  bob:
    image: "doichain/node-only:0.16.3.2"
    hostname: bob
    ports:
      - "18544:18332"
    expose:
      - "18332"
    environment:
      - REGTEST=true
      - RPC_ALLOW_IP=::/0
      - RPC_PASSWORD=generated-password
      - DAPP_URL=http://172.20.0.8:4000
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.0.7

  regtest:
    image: "doichain/dapp-only"
    hostname: regtest
    #build: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/home/doichain/dapp" #TODO you can enable this during development but not during testing in CI (permission denided)
    dns:
      - 172.20.0.5
      - 8.8.8.8
    dns_search: ci-doichain.org
    #&& export MONGO_URL=mongodb://mongo:27017/alice && meteor npm cache verify && meteor npm install && meteor npm run test-d-compose-alice-mocha
    command: bash -c "./contrib/scripts/meteor/start_dapp.sh && sleep infinity"
    ports:
      - "3000:3000"
      - "4000:4000"
    expose:
      - "3000"
      - "4000"
    stdin_open: true
    tty: true
    depends_on:
      - alice
      - bob
      - bind
      - mail
    networks:
        static-network:
          ipv4_address: 172.20.0.8

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
